### ISSUE TITLE
Feature request: Angle of the area Lines

### ISSUE THREAD

**Issue by AndyVRD** [snowzach/doods#63]
Hi,

Will it be possible to add a option for change the angle of the area variable setting? My camera is on the corner of my house and if i add a 10% for the top of the image there is only a little part that is covered because of the angle of the camera. Will be great if you can set a angle for the line. :)

**Comment by snowzach** [comment]
Hi @AndyVRD, unfortunately it would not be possible to do anything at an angle. Most of the magic of DOODS comes from the models that do the object detection. The standard is pretty much to return boxes. DOODS knows how to process the output and wraps it in an API. There's really no way to provide an angle. The only thing I can suggest, assuming you are using this via home assistant, is to experiment with the covers option. If you set covers = false than any part of the object detected inside of the box will trigger so if you get the box close to what you want to detect, even a piece in the box will trigger detection rather than requiring the entire object inside of the box.

**Comment by danededane** [comment]
If it's possible in any future versions I say +1 on this request :)

**Comment by shadow05139** [comment]
Boxes just don't work for my cameras I have zones that I don't want to alert on  neighbors  and  people walking on the foot path and bushes that are 90% confidence a person at night lol  I just really want to make this work.

I can provide examples if needed

**Comment by snowzach** [comment]
I am working on an update to DOODS now that should make it a little more flexible. Essentially you will be able to set boxes and say specifically what you want to detect in that box. It will also extend the `covers` option so if any part of the object is inside the box it will fire. So while it will not allow defining a shape, you could instead define 3 smaller boxes and say if any part of a `car` is inside any of those boxes, then trigger. 

For instance... something like this 
![image](https://user-images.githubusercontent.com/7305473/144748834-849a7fce-c432-40ab-a360-3fa9703d8155.png)
So if any detected person > 60% is inside of that big box it will trigger or any part of a car at > 50% is inside either of those 2 littler boxes it will fire.

**Comment by shadow05139** [comment]
Thanks snowzach, look forward to this update

**Comment by snowzach** [comment]
It's complete: https://github.com/snowzach/doods2 The home assistant module supports this as well.
